repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^examples/
      - id: ruff-format
        exclude: ^examples/
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: ^examples/
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        exclude: ^examples/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^src/
        exclude: ^examples/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
        exclude: ^examples/
      - id: check-docstring-first
        exclude: ^examples/
      - id: check-merge-conflict
        exclude: ^examples/
      - id: check-toml
        exclude: ^examples/
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^examples/
      - id: trailing-whitespace
        exclude: ^examples/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            dagster,
            "dask[array]",
            click,
            google-cloud-storage,
            google-auth-httplib2,
            google-api-python-client,
            inquirer,
            loguru,
            matplotlib<3.9,
            numcodecs,
            numpy<2,
            pydantic,
            pandas-stubs,
            pytest,
            pyfakefs,
            pytest-mock,
            types-tqdm,
            types-Pillow,
            types-requests,
            xlsxwriter,
            types-PyYAML,
            simpleitk,
          ]
        args: [--config-file, pyproject.toml]
        exclude: ^examples/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--write-changes, --skip, "*.log"]
        exclude: ^examples/
