site_name: Cardiotensor
site_url: https://mydomain.org/mysite
site_author: Joseph Brunet
site_description: >-
  Toolkit designed for quantifying and visualising 3D cardiomyocytes orientations in heart images

# Repository
repo_name: cardiotensor
repo_url: https://github.com/JosephBrunet/cardiotensor

edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 - 2025 - Joseph Brunet

theme:
  name: material
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  logo: assets/favicon.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github # (1)!
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago


# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JosephBrunet
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cardiotensor/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Joseph__Brunet


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mkdocstrings





# Page tree
nav:
  - Installation: installation.md
  - Examples: examples.md
  - Configuration file: configuration.md
  - Contributing: contributing.md
  - Citing: citing.md

