[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm"
]

[project]
version = "1.0.0"
authors = [
    { email = "j.brunet@ucl.ac.uk", name = "Joseph Brunet" }
]
classifiers = [
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Typing :: Typed"
]
dependencies = [
    "cupy-cuda12x",
    "dask",
    "dask-image",
    "matplotlib",
    "numpy",
    "opencv-python",
    "pillow",
    "scikit-image",
    "structure-tensor",
    "tifffile",
]
description = "Toolkit designed for quantifying 3D cardiomyocytes orientations in heart images"
keywords = []
name = "MyoTensor"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.md" }

[project.scripts]
myotensor = "MyoTensor.processing_heart:main"

[project.urls]
homepage = "https://github.com/JosephBrunet/image-processing-utils"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
plugins = [
    "pydantic.mypy"
]
python_version = "3.8"
strict = true

[[tool.mypy.overrides]]
module = "glymur.*"
ignore_missing_imports = true

[tool.ruff]
fix = true
force-exclude = true
select = [
    "F401",  # Remove unused imports
    "I",  # Sort imports
    "UP"  # Update Python syntax
]
target-version = "py38"
isort.known-first-party = [
    "image_processing_utils"
]
mccabe.max-complexity = 18
pep8-naming.classmethod-decorators = [
    "classmethod",
    "pydantic.validator"
]

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false