name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tools
        run: pip install black ruff

      - name: Run Ruff
        run: ruff check .

      # - name: Run Black
      #   run: black --check .

  nox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Ensure versions are strings

    steps:
      # Set debug environment variable
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Upgrade pip and install nox
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox

      # Run Nox sessions
      - name: Run Nox
        run: nox --python ${{ matrix.python-version }}