name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Use valid Python versions

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Upgrade pip and install nox
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox

      # Run Nox sessions
      - name: Run Nox
        run: nox